= TODO items

== Bugs
- Handle case where index file already exists (during index start or during index dump)
- Permissions setuid and setgid may get lost when ownership changes (on Linux only setuid)
- Bind mounts are processed multiple times (could be avoided ?)


== Features
- Create a renumber/restore log file (based on index filename)
- Add options to select specific restore uids/gids (-U 12,23 or -G 32,21)
- Add option to not cross file system boundaries (-x / --one-file-system)


== Improvements
- Implement better subcommand support (but argparse does not ship with RHEL5)
- Support both 'renumid renumber' and 'renumid-renumber' calls maybe ?
- Make renumid Unix-agnostic (renumid currently relies on /proc/mounts and /proc/stat)


== Index file format v2
- Store setuid and setgid bits
- Store both uid and gid per path (more efficiently handle paths requiring both changes)
- Use something better than pickle ?
- Compress index file


== New use-cases
- Option to create a full file system index (discard the mapping)
- Option to switch renumber/restore based on uidmap/gidmap or complete store
- Apply operations in 'chrooted' mode (in case filesystems are mounted elsewhere)
- Report which files have ACLs configured (optional based on pylibacl support ?)
